# Generated by Django 4.1.7 on 2023-03-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.BooleanField()),
                ('female', models.BooleanField()),
                ('kids', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing', models.BooleanField()),
                ('shoes', models.BooleanField()),
                ('bags', models.BooleanField()),
                ('accessories', models.BooleanField()),
            ],
        ),
    ]
