# Generated by Django 4.1.7 on 2023-03-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='item_main_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='all_items.maincategory'),
        ),
    ]
