# Generated by Django 4.1.7 on 2023-03-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_items', '0002_subcategory_item_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='item_main_category',
        ),
    ]
