# Generated by Django 4.1.7 on 2023-03-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_items', '0003_remove_subcategory_item_main_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='female',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='accessories',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='male',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='bags',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='clothing',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='shoes',
        ),
    ]
