# Generated by Django 4.1.7 on 2023-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_items', '0004_rename_female_maincategory_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='main_category',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
