# Generated by Django 4.1.7 on 2023-03-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_items', '0006_clothingsize_colors_shoessize_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloth_size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='all_items.clothingsize'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='all_items.colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='sh_size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='all_items.shoessize'),
        ),
    ]
