# Generated by Django 4.1.7 on 2023-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
