# Generated by Django 4.1.7 on 2023-03-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='add_image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(default='default.png', upload_to='item_images'),
        ),
    ]
