# Generated by Django 4.1.7 on 2023-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_add_image_image_image_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
