# Generated by Django 4.1.7 on 2023-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_image',
            field=models.ImageField(default='default.img', upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_clothing_size',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_main_category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_subcategory',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories')], default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
