# Generated by Django 4.1.7 on 2023-03-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_add_image_alter_item_add_clothing_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='add_clothing_size',
            field=models.CharField(choices=[('select', 'Select'), ('s', 'S'), ('m', 'M'), ('l', 'L')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_color',
            field=models.CharField(choices=[('select', 'Select'), ('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_main_category',
            field=models.CharField(choices=[('select', 'Select'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_shoes_size',
            field=models.CharField(choices=[('select', 'Select'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_subcategory',
            field=models.CharField(choices=[('select', 'Select'), ('clothing', 'Clothing'), ('shoes', 'Shoes'), ('bags', 'Bags'), ('accessories', 'Accessories')], default=None, max_length=50),
        ),
    ]
