# Generated by Django 4.1.7 on 2023-03-26 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_alter_profile_gender_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccountOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('buyer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.shoppingbag')),
                ('owner_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Company Name', max_length=50)),
                ('company_email', models.EmailField(default='Company Email', max_length=254)),
                ('company_phone', models.IntegerField()),
                ('company_image', models.ImageField(default='default.png', upload_to='company_images')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
