# Generated by Django 4.1.7 on 2023-03-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_add_clothing_size_alter_item_add_color_and_more'),
        ('business_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccountorders',
            name='buyer_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
