# Generated by Django 4.1.7 on 2023-03-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_shoppingbag_item_id_shoppingbag_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_fields',
            field=models.CharField(choices=[('select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='-', max_length=50),
        ),
    ]
