# Generated by Django 4.1.7 on 2023-03-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_gender_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(default=140718126068584, on_delete=django.db.models.deletion.CASCADE, to='user_profile.gender'),
        ),
    ]
