# Generated by Django 4.1.7 on 2023-03-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_maincategory_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
