# Generated by Django 4.1.7 on 2023-03-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
