# Generated by Django 4.1.7 on 2023-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_profile_gender_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender_fields',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('-', '-')], default='-', max_length=50),
        ),
    ]
