# Generated by Django 4.1.7 on 2023-03-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/default.png', upload_to='profile_pics'),
        ),
    ]
